// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: hamster_woods_contract.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace Contracts.HamsterWoods {

  #region Events
  public partial class RankingRulesUpdated : aelf::IEvent<RankingRulesUpdated>
  {
    public global::System.Collections.Generic.IEnumerable<RankingRulesUpdated> GetIndexed()
    {
      return new List<RankingRulesUpdated>
      {
      };
    }

    public RankingRulesUpdated GetNonIndexed()
    {
      return new RankingRulesUpdated
      {
        BeginTime = BeginTime,
        WeeklyTournamentBeginNum = WeeklyTournamentBeginNum,
        RankingHours = RankingHours,
        PublicityHours = PublicityHours,
        RankingPlayerCount = RankingPlayerCount,
        PublicityPlayerCount = PublicityPlayerCount,
      };
    }
  }

  public partial class Picked : aelf::IEvent<Picked>
  {
    public global::System.Collections.Generic.IEnumerable<Picked> GetIndexed()
    {
      return new List<Picked>
      {
      };
    }

    public Picked GetNonIndexed()
    {
      return new Picked
      {
        GridType = GridType,
        GridNum = GridNum,
        Score = Score,
        BingoBlockHeight = BingoBlockHeight,
        PlayerAddress = PlayerAddress,
        DiceCount = DiceCount,
        DiceNumbers = DiceNumbers,
        StartGridNum = StartGridNum,
        EndGridNum = EndGridNum,
        WeeklyAcorns = WeeklyAcorns,
        TotalAcorns = TotalAcorns,
        TotalChance = TotalChance,
        IsRace = IsRace,
        WeekNum = WeekNum,
        AcornsDecimals = AcornsDecimals,
      };
    }
  }

  public partial class AcornsUnlocked : aelf::IEvent<AcornsUnlocked>
  {
    public global::System.Collections.Generic.IEnumerable<AcornsUnlocked> GetIndexed()
    {
      return new List<AcornsUnlocked>
      {
      };
    }

    public AcornsUnlocked GetNonIndexed()
    {
      return new AcornsUnlocked
      {
        From = From,
        To = To,
        Symbol = Symbol,
        Amount = Amount,
        WeekNum = WeekNum,
      };
    }
  }

  public partial class ChancePurchased : aelf::IEvent<ChancePurchased>
  {
    public global::System.Collections.Generic.IEnumerable<ChancePurchased> GetIndexed()
    {
      return new List<ChancePurchased>
      {
      };
    }

    public ChancePurchased GetNonIndexed()
    {
      return new ChancePurchased
      {
        PlayerAddress = PlayerAddress,
        AcornsAmount = AcornsAmount,
        ChanceCount = ChanceCount,
        WeeklyAcorns = WeeklyAcorns,
        TotalAcorns = TotalAcorns,
        TotalChance = TotalChance,
      };
    }
  }

  #endregion
  public static partial class HamsterWoodsContractContainer
  {
    static readonly string __ServiceName = "HamsterWoodsContract";

    #region Marshallers
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.PlayInput> __Marshaller_PlayInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.PlayInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.Int32Value> __Marshaller_google_protobuf_Int32Value = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Int32Value.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.GameLimitSettings> __Marshaller_GameLimitSettings = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.GameLimitSettings.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::AElf.Types.Address> __Marshaller_aelf_Address = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AElf.Types.Address.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.GameRules> __Marshaller_GameRules = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.GameRules.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.RankingRules> __Marshaller_RankingRules = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.RankingRules.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.PurchaseChanceConfig> __Marshaller_PurchaseChanceConfig = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.PurchaseChanceConfig.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.UnlockAcornsInput> __Marshaller_UnlockAcornsInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.UnlockAcornsInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.RaceConfig> __Marshaller_RaceConfig = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.RaceConfig.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Google.Protobuf.WellKnownTypes.BoolValue> __Marshaller_google_protobuf_BoolValue = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.BoolValue.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.PlayerInformation> __Marshaller_PlayerInformation = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.PlayerInformation.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.GetBoutInformationInput> __Marshaller_GetBoutInformationInput = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.GetBoutInformationInput.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.BoutInformation> __Marshaller_BoutInformation = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.BoutInformation.Parser.ParseFrom);
    static readonly aelf::Marshaller<global::Contracts.HamsterWoods.LockedAcornsInfoList> __Marshaller_LockedAcornsInfoList = aelf::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Contracts.HamsterWoods.LockedAcornsInfoList.Parser.ParseFrom);
    #endregion

    #region Methods
    static readonly aelf::Method<global::Contracts.HamsterWoods.PlayInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Play = new aelf::Method<global::Contracts.HamsterWoods.PlayInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Play",
        __Marshaller_PlayInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty> __Method_PurchaseChance = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Int32Value, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "PurchaseChance",
        __Marshaller_google_protobuf_Int32Value,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Contracts.HamsterWoods.GameLimitSettings, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetGameLimitSettings = new aelf::Method<global::Contracts.HamsterWoods.GameLimitSettings, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetGameLimitSettings",
        __Marshaller_GameLimitSettings,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_Initialize = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "Initialize",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_ChangeAdmin = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "ChangeAdmin",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Contracts.HamsterWoods.GameRules, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetGameRules = new aelf::Method<global::Contracts.HamsterWoods.GameRules, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetGameRules",
        __Marshaller_GameRules,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Contracts.HamsterWoods.RankingRules, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRankingRules = new aelf::Method<global::Contracts.HamsterWoods.RankingRules, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRankingRules",
        __Marshaller_RankingRules,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Contracts.HamsterWoods.PurchaseChanceConfig, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetPurchaseChanceConfig = new aelf::Method<global::Contracts.HamsterWoods.PurchaseChanceConfig, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetPurchaseChanceConfig",
        __Marshaller_PurchaseChanceConfig,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetUnlockManager = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetUnlockManager",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Contracts.HamsterWoods.UnlockAcornsInput, global::Google.Protobuf.WellKnownTypes.Empty> __Method_BatchUnlockAcorns = new aelf::Method<global::Contracts.HamsterWoods.UnlockAcornsInput, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "BatchUnlockAcorns",
        __Marshaller_UnlockAcornsInput,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_StartRace = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "StartRace",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_StopRace = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "StopRace",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::Contracts.HamsterWoods.RaceConfig, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SetRaceConfig = new aelf::Method<global::Contracts.HamsterWoods.RaceConfig, global::Google.Protobuf.WellKnownTypes.Empty>(
        aelf::MethodType.Action,
        __ServiceName,
        "SetRaceConfig",
        __Marshaller_RaceConfig,
        __Marshaller_google_protobuf_Empty);

    static readonly aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue> __Method_CheckHamsterPass = new aelf::Method<global::AElf.Types.Address, global::Google.Protobuf.WellKnownTypes.BoolValue>(
        aelf::MethodType.View,
        __ServiceName,
        "CheckHamsterPass",
        __Marshaller_aelf_Address,
        __Marshaller_google_protobuf_BoolValue);

    static readonly aelf::Method<global::AElf.Types.Address, global::Contracts.HamsterWoods.PlayerInformation> __Method_GetPlayerInformation = new aelf::Method<global::AElf.Types.Address, global::Contracts.HamsterWoods.PlayerInformation>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPlayerInformation",
        __Marshaller_aelf_Address,
        __Marshaller_PlayerInformation);

    static readonly aelf::Method<global::Contracts.HamsterWoods.GetBoutInformationInput, global::Contracts.HamsterWoods.BoutInformation> __Method_GetBoutInformation = new aelf::Method<global::Contracts.HamsterWoods.GetBoutInformationInput, global::Contracts.HamsterWoods.BoutInformation>(
        aelf::MethodType.View,
        __ServiceName,
        "GetBoutInformation",
        __Marshaller_GetBoutInformationInput,
        __Marshaller_BoutInformation);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address> __Method_GetAdmin = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::AElf.Types.Address>(
        aelf::MethodType.View,
        __ServiceName,
        "GetAdmin",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_aelf_Address);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.GameLimitSettings> __Method_GetGameLimitSettings = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.GameLimitSettings>(
        aelf::MethodType.View,
        __ServiceName,
        "GetGameLimitSettings",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_GameLimitSettings);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.GameRules> __Method_GetGameRules = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.GameRules>(
        aelf::MethodType.View,
        __ServiceName,
        "GetGameRules",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_GameRules);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.RankingRules> __Method_GetRankingRules = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.RankingRules>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRankingRules",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_RankingRules);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.PurchaseChanceConfig> __Method_GetPurchaseChanceConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.PurchaseChanceConfig>(
        aelf::MethodType.View,
        __ServiceName,
        "GetPurchaseChanceConfig",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_PurchaseChanceConfig);

    static readonly aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.RaceConfig> __Method_GetRaceConfig = new aelf::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Contracts.HamsterWoods.RaceConfig>(
        aelf::MethodType.View,
        __ServiceName,
        "GetRaceConfig",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_RaceConfig);

    static readonly aelf::Method<global::AElf.Types.Address, global::Contracts.HamsterWoods.LockedAcornsInfoList> __Method_GetLockedAcornsInfoList = new aelf::Method<global::AElf.Types.Address, global::Contracts.HamsterWoods.LockedAcornsInfoList>(
        aelf::MethodType.View,
        __ServiceName,
        "GetLockedAcornsInfoList",
        __Marshaller_aelf_Address,
        __Marshaller_LockedAcornsInfoList);

    #endregion

    #region Descriptors
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Contracts.HamsterWoods.HamsterWoodsContractReflection.Descriptor.Services[0]; }
    }

    public static global::System.Collections.Generic.IReadOnlyList<global::Google.Protobuf.Reflection.ServiceDescriptor> Descriptors
    {
      get
      {
        return new global::System.Collections.Generic.List<global::Google.Protobuf.Reflection.ServiceDescriptor>()
        {
          global::AElf.Standards.ACS12.Acs12Reflection.Descriptor.Services[0],
          global::Contracts.HamsterWoods.HamsterWoodsContractReflection.Descriptor.Services[0],
        };
      }
    }
    #endregion

  }
}
#endregion

